name: ci
on:
  push:
    branches:
      - master
      #- main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: True
      - run: ls docs/co-connect-tools
      - name: Install co-connect-tools
        run:  pip install -e docs/co-connect-tools
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install mkdocs-material
      - run: pip install mknotebooks
      - run: pip install mkdocstrings
      - run: mkdocs gh-deploy --force
