name: ci
on:
  push:
    branches:
      - master
      #- main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.0
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - run: pip3 install -r requirements.txt
      - run: ls
      - run: ls public
      - run: ls public/docs/
      - run: ls public/docs/CoConnectTools/
      - run: ls public/docs/CoConnectTools/source_code
      - name: deploy
        run: |
          cd public
          pwd
          ls
          mkdocs gh-deploy --force
