name: ci
on:
  push:
    branches:
      - master
      #- main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/checkout@v2
        with:
          submodules: True
      - run: ls docs/co-connect-tools
      - name: Install setuptools
        run: pip3 install setuptools
      - name: Install co-connect-tools
        run:  pip3 install -e docs/co-connect-tools
      - run: pip3 install -r requirements.txt
      - run: mkdocs gh-deploy --force
